/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pcricketstats;

import java.util.ArrayList;

/**
 *
 * @author interkiwiwebdev
 */
public class AppInterface extends javax.swing.JFrame {

    private ArrayList<Player> players;
    /**
     * Creates new form AppInterface
     */
    public AppInterface(ArrayList<Player> players) {
        initComponents();
        this.players = players;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainAppTabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainPanelPlayerStats = new javax.swing.JPanel();
        searchPlayerNameLabel = new javax.swing.JLabel();
        getPlayerName = new javax.swing.JTextField();
        getPlayerStatsBtn = new javax.swing.JButton();
        playerStatsPanel = new javax.swing.JPanel();
        playerNameLabel = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        countryNameLabel = new javax.swing.JLabel();
        countryName = new javax.swing.JLabel();
        careerSpanLabel = new javax.swing.JLabel();
        careerSpan = new javax.swing.JLabel();
        careerLengthLabel = new javax.swing.JLabel();
        careerLength = new javax.swing.JLabel();
        matchesPlayedLabel = new javax.swing.JLabel();
        matchesPlayed = new javax.swing.JLabel();
        inningsPlayedLabel = new javax.swing.JLabel();
        inningsPlayed = new javax.swing.JLabel();
        ballsBowledLabel = new javax.swing.JLabel();
        ballsBowled = new javax.swing.JLabel();
        runsConcededLabel = new javax.swing.JLabel();
        runsConceded = new javax.swing.JLabel();
        wicketsTakenLabel = new javax.swing.JLabel();
        wicketsTaken = new javax.swing.JLabel();
        bowlingAverageLabel = new javax.swing.JLabel();
        bowlingAverage = new javax.swing.JLabel();
        economyRateLabel = new javax.swing.JLabel();
        economyRate = new javax.swing.JLabel();
        strikeRateLabel = new javax.swing.JLabel();
        strikeRate = new javax.swing.JLabel();
        fiveWicketsInningsLabel = new javax.swing.JLabel();
        fiveWicketsPerInnings = new javax.swing.JLabel();
        countryFlagPanel = new javax.swing.JPanel();
        compareStatsPanel = new javax.swing.JPanel();
        compareStatsLabel = new javax.swing.JLabel();
        chooseGraphLabel = new javax.swing.JLabel();
        chooseGraphOption = new javax.swing.JComboBox();
        confirmGraphBtn = new javax.swing.JButton();
        displayGraphPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        multiplePlayerStatsPanel = new javax.swing.JPanel();
        multiplePlayerStatsLabel = new javax.swing.JLabel();
        getAllPlayersBtn = new javax.swing.JButton();
        playersDataScrollTable = new javax.swing.JScrollPane();
        playersDataTable = new javax.swing.JTable();
        retrievePlayerDataPanel = new javax.swing.JPanel();
        playersFromLabel = new javax.swing.JLabel();
        getPlayerFrom = new javax.swing.JTextField();
        playersToLabel = new javax.swing.JLabel();
        getPlayerTo = new javax.swing.JTextField();
        getFromToPlayersBtn = new javax.swing.JButton();
        getFirstLabel = new javax.swing.JLabel();
        firstNPlayers = new javax.swing.JTextField();
        nPlayersLabel = new javax.swing.JLabel();
        getNPlayersBtn = new javax.swing.JButton();
        getPlayersFromLabel = new javax.swing.JLabel();
        fromCountryOption = new javax.swing.JComboBox();
        getPlayersFromCountryBtn = new javax.swing.JButton();
        countryVsCountryPanel = new javax.swing.JPanel();
        compareStatsComboBox = new javax.swing.JComboBox();
        comparePlayerStatsLabel = new javax.swing.JLabel();
        comparePlayerStatsBtn = new javax.swing.JButton();
        graphDisplayPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        displayPlayerAveragesBtn = new javax.swing.JButton();
        promptLabel = new javax.swing.JLabel();
        aveCareerSpanLabel = new javax.swing.JLabel();
        aveCareerSpan = new javax.swing.JLabel();
        aveCareerLengthLabel = new javax.swing.JLabel();
        aveCareerLength = new javax.swing.JLabel();
        aveMatchesPlayedLabel = new javax.swing.JLabel();
        aveMatchesPlayed = new javax.swing.JLabel();
        aveInningsPlayedLabel = new javax.swing.JLabel();
        aveInningsPlayed = new javax.swing.JLabel();
        aveBallsBowledLabel = new javax.swing.JLabel();
        aveBallsBowled = new javax.swing.JLabel();
        aveRunsConcededLabel = new javax.swing.JLabel();
        aveRunsConceded = new javax.swing.JLabel();
        aveWicketsTakenLabel = new javax.swing.JLabel();
        aveWicketsTaken = new javax.swing.JLabel();
        aveBowlingAverageLabel = new javax.swing.JLabel();
        aveBowlingAverage = new javax.swing.JLabel();
        aveEconomyRateLabel = new javax.swing.JLabel();
        aveEconomyRate = new javax.swing.JLabel();
        aveStrikeRateLabel = new javax.swing.JLabel();
        aveStrikeRate = new javax.swing.JLabel();
        ave5wicketsInningsLabel = new javax.swing.JLabel();
        aveFiveWicketsPerInnings = new javax.swing.JLabel();
        closeBtn1 = new javax.swing.JButton();
        sortByComboBox = new javax.swing.JComboBox();
        sortByLabel = new javax.swing.JLabel();
        sortBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1350, 671));
        setMinimumSize(new java.awt.Dimension(1350, 671));
        setResizable(false);

        mainAppTabPane.setBackground(new java.awt.Color(0, 48, 88));
        mainAppTabPane.setMaximumSize(new java.awt.Dimension(1350, 671));
        mainAppTabPane.setMinimumSize(new java.awt.Dimension(1350, 671));
        mainAppTabPane.setOpaque(true);
        mainAppTabPane.setPreferredSize(new java.awt.Dimension(1350, 671));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(1350, 643));
        jPanel1.setMinimumSize(new java.awt.Dimension(1350, 643));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 643));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Single Player Stats");

        mainPanelPlayerStats.setBackground(new java.awt.Color(211, 225, 255));
        mainPanelPlayerStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));
        mainPanelPlayerStats.setMaximumSize(new java.awt.Dimension(412, 350));
        mainPanelPlayerStats.setMinimumSize(new java.awt.Dimension(412, 350));
        mainPanelPlayerStats.setPreferredSize(new java.awt.Dimension(412, 350));

        searchPlayerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchPlayerNameLabel.setText("Name of the player you want stats for:");

        getPlayerName.setText("getPlayerName");

        getPlayerStatsBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getPlayerStatsBtn.setText("Get Player Stats");

        playerStatsPanel.setBackground(new java.awt.Color(255, 255, 255));
        playerStatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        playerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerNameLabel.setText("Player Name:");

        playerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        playerName.setName("playerName"); // NOI18N

        countryNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countryNameLabel.setText("Country:");

        countryName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        countryName.setName("countryName"); // NOI18N

        careerSpanLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        careerSpanLabel.setText("Career Span:");

        careerSpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        careerSpan.setName("careerSpan"); // NOI18N

        careerLengthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        careerLengthLabel.setText("Career Length:");

        careerLength.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        careerLength.setName("careerLength"); // NOI18N

        matchesPlayedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        matchesPlayedLabel.setText("Matches Played:");

        matchesPlayed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        matchesPlayed.setName("matchesPlayed"); // NOI18N

        inningsPlayedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inningsPlayedLabel.setText("Innings Played:");

        inningsPlayed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inningsPlayed.setName("inningsPlayed"); // NOI18N

        ballsBowledLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ballsBowledLabel.setText("Balls Bowled:");

        ballsBowled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ballsBowled.setName("ballsBowled"); // NOI18N

        runsConcededLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        runsConcededLabel.setText("Runs Conceded:");

        runsConceded.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        runsConceded.setName("runsConceded"); // NOI18N

        wicketsTakenLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wicketsTakenLabel.setText("Wickets Taken:");

        wicketsTaken.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wicketsTaken.setName("wicketsTaken"); // NOI18N

        bowlingAverageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bowlingAverageLabel.setText("Bowling Average:");

        bowlingAverage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bowlingAverage.setName("bowlingAverage"); // NOI18N

        economyRateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        economyRateLabel.setText("Economy Rate:");

        economyRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        economyRate.setName("economyRate"); // NOI18N

        strikeRateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        strikeRateLabel.setText("Strike Rate:");

        strikeRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        strikeRate.setName("strikeRate"); // NOI18N

        fiveWicketsInningsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fiveWicketsInningsLabel.setText("5 Wickets / Innings:");

        fiveWicketsPerInnings.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fiveWicketsPerInnings.setName("5wicketsPerInnings"); // NOI18N

        countryFlagPanel.setBackground(new java.awt.Color(211, 225, 255));
        countryFlagPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));
        countryFlagPanel.setMaximumSize(new java.awt.Dimension(155, 117));
        countryFlagPanel.setMinimumSize(new java.awt.Dimension(155, 117));
        countryFlagPanel.setRequestFocusEnabled(false);
        countryFlagPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout countryFlagPanelLayout = new javax.swing.GroupLayout(countryFlagPanel);
        countryFlagPanel.setLayout(countryFlagPanelLayout);
        countryFlagPanelLayout.setHorizontalGroup(
            countryFlagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        countryFlagPanelLayout.setVerticalGroup(
            countryFlagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout playerStatsPanelLayout = new javax.swing.GroupLayout(playerStatsPanel);
        playerStatsPanel.setLayout(playerStatsPanelLayout);
        playerStatsPanelLayout.setHorizontalGroup(
            playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(countryNameLabel)
                    .addComponent(careerLengthLabel)
                    .addComponent(matchesPlayedLabel)
                    .addComponent(inningsPlayedLabel)
                    .addComponent(ballsBowledLabel)
                    .addComponent(runsConcededLabel)
                    .addComponent(wicketsTakenLabel)
                    .addComponent(bowlingAverageLabel)
                    .addComponent(economyRateLabel)
                    .addComponent(strikeRateLabel)
                    .addComponent(fiveWicketsInningsLabel)
                    .addComponent(playerNameLabel)
                    .addComponent(careerSpanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerStatsPanelLayout.createSequentialGroup()
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countryName)
                            .addComponent(playerName)
                            .addComponent(careerSpan)
                            .addComponent(careerLength)
                            .addComponent(matchesPlayed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(countryFlagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playerStatsPanelLayout.createSequentialGroup()
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inningsPlayed)
                            .addComponent(ballsBowled)
                            .addComponent(runsConceded)
                            .addComponent(wicketsTaken)
                            .addComponent(bowlingAverage)
                            .addComponent(economyRate)
                            .addComponent(strikeRate)
                            .addComponent(fiveWicketsPerInnings))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        playerStatsPanelLayout.setVerticalGroup(
            playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(playerStatsPanelLayout.createSequentialGroup()
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playerNameLabel)
                            .addComponent(playerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryNameLabel)
                            .addComponent(countryName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(careerSpanLabel)
                            .addComponent(careerSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(careerLengthLabel)
                            .addComponent(careerLength))
                        .addGap(13, 13, 13)
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matchesPlayedLabel)
                            .addComponent(matchesPlayed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inningsPlayedLabel)
                            .addComponent(inningsPlayed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ballsBowledLabel)
                            .addComponent(ballsBowled)))
                    .addComponent(countryFlagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runsConcededLabel)
                    .addComponent(runsConceded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wicketsTakenLabel)
                    .addComponent(wicketsTaken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bowlingAverageLabel)
                    .addComponent(bowlingAverage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(economyRateLabel)
                    .addComponent(economyRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strikeRateLabel)
                    .addComponent(strikeRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiveWicketsInningsLabel)
                    .addComponent(fiveWicketsPerInnings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelPlayerStatsLayout = new javax.swing.GroupLayout(mainPanelPlayerStats);
        mainPanelPlayerStats.setLayout(mainPanelPlayerStatsLayout);
        mainPanelPlayerStatsLayout.setHorizontalGroup(
            mainPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelPlayerStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerStatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelPlayerStatsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(getPlayerStatsBtn))
                    .addGroup(mainPanelPlayerStatsLayout.createSequentialGroup()
                        .addComponent(searchPlayerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getPlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelPlayerStatsLayout.setVerticalGroup(
            mainPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelPlayerStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchPlayerNameLabel)
                    .addComponent(getPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getPlayerStatsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerStatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        compareStatsPanel.setBackground(new java.awt.Color(211, 225, 255));
        compareStatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        compareStatsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compareStatsLabel.setText("Compare Stats - Player vs Country vs Overall");

        chooseGraphLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chooseGraphLabel.setText("Choose Graph:");

        chooseGraphOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        confirmGraphBtn.setText("Go");
        confirmGraphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmGraphBtnActionPerformed(evt);
            }
        });

        displayGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayGraphPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        javax.swing.GroupLayout displayGraphPanelLayout = new javax.swing.GroupLayout(displayGraphPanel);
        displayGraphPanel.setLayout(displayGraphPanelLayout);
        displayGraphPanelLayout.setHorizontalGroup(
            displayGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayGraphPanelLayout.setVerticalGroup(
            displayGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout compareStatsPanelLayout = new javax.swing.GroupLayout(compareStatsPanel);
        compareStatsPanel.setLayout(compareStatsPanelLayout);
        compareStatsPanelLayout.setHorizontalGroup(
            compareStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compareStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compareStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(compareStatsPanelLayout.createSequentialGroup()
                        .addComponent(compareStatsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(chooseGraphLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chooseGraphOption, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmGraphBtn)))
                .addContainerGap())
        );
        compareStatsPanelLayout.setVerticalGroup(
            compareStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compareStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compareStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compareStatsLabel)
                    .addComponent(chooseGraphLabel)
                    .addComponent(chooseGraphOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmGraphBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        closeBtn.setText("Close Application");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanelPlayerStats, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(compareStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compareStatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanelPlayerStats, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        mainAppTabPane.addTab("Single Player Stats", jPanel1);

        multiplePlayerStatsPanel.setBackground(new java.awt.Color(153, 153, 153));
        multiplePlayerStatsPanel.setMaximumSize(new java.awt.Dimension(1350, 643));
        multiplePlayerStatsPanel.setMinimumSize(new java.awt.Dimension(1350, 643));

        multiplePlayerStatsLabel.setFont(multiplePlayerStatsLabel.getFont().deriveFont(multiplePlayerStatsLabel.getFont().getStyle() | java.awt.Font.BOLD, multiplePlayerStatsLabel.getFont().getSize()+13));
        multiplePlayerStatsLabel.setText("Multiple Player Stats");

        getAllPlayersBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getAllPlayersBtn.setText("Get All Players");
        getAllPlayersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllPlayersBtnActionPerformed(evt);
            }
        });

        playersDataTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));
        playersDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Player Name", "Country", "Career Span", "Matches Played", "Innings Played", "Balls Bowled", "Runs Conceded", "Wickets Taken", "Bowling Average", "Economy Rate", "Strike Rate", "5 Wickets/Innings"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        playersDataTable.setPreferredSize(new java.awt.Dimension(700, 160));
        playersDataTable.getTableHeader().setReorderingAllowed(false);
        playersDataScrollTable.setViewportView(playersDataTable);
        playersDataTable.getColumnModel().getColumn(0).setResizable(false);
        playersDataTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        playersDataTable.getColumnModel().getColumn(0).setHeaderValue("ID");
        playersDataTable.getColumnModel().getColumn(1).setResizable(false);
        playersDataTable.getColumnModel().getColumn(1).setHeaderValue("Player Name");
        playersDataTable.getColumnModel().getColumn(2).setResizable(false);
        playersDataTable.getColumnModel().getColumn(2).setHeaderValue("Country");
        playersDataTable.getColumnModel().getColumn(3).setResizable(false);
        playersDataTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        playersDataTable.getColumnModel().getColumn(3).setHeaderValue("Career Span");
        playersDataTable.getColumnModel().getColumn(4).setResizable(false);
        playersDataTable.getColumnModel().getColumn(4).setPreferredWidth(60);
        playersDataTable.getColumnModel().getColumn(4).setHeaderValue("Matches Played");
        playersDataTable.getColumnModel().getColumn(5).setResizable(false);
        playersDataTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        playersDataTable.getColumnModel().getColumn(5).setHeaderValue("Innings Played");
        playersDataTable.getColumnModel().getColumn(6).setResizable(false);
        playersDataTable.getColumnModel().getColumn(6).setPreferredWidth(50);
        playersDataTable.getColumnModel().getColumn(6).setHeaderValue("Balls Bowled");
        playersDataTable.getColumnModel().getColumn(7).setResizable(false);
        playersDataTable.getColumnModel().getColumn(7).setPreferredWidth(60);
        playersDataTable.getColumnModel().getColumn(7).setHeaderValue("Runs Conceded");
        playersDataTable.getColumnModel().getColumn(8).setResizable(false);
        playersDataTable.getColumnModel().getColumn(8).setPreferredWidth(50);
        playersDataTable.getColumnModel().getColumn(8).setHeaderValue("Wickets Taken");
        playersDataTable.getColumnModel().getColumn(9).setResizable(false);
        playersDataTable.getColumnModel().getColumn(9).setPreferredWidth(55);
        playersDataTable.getColumnModel().getColumn(9).setHeaderValue("Bowling Average");
        playersDataTable.getColumnModel().getColumn(10).setResizable(false);
        playersDataTable.getColumnModel().getColumn(10).setPreferredWidth(50);
        playersDataTable.getColumnModel().getColumn(10).setHeaderValue("Economy Rate");
        playersDataTable.getColumnModel().getColumn(11).setResizable(false);
        playersDataTable.getColumnModel().getColumn(11).setPreferredWidth(35);
        playersDataTable.getColumnModel().getColumn(11).setHeaderValue("Strike Rate");
        playersDataTable.getColumnModel().getColumn(12).setResizable(false);
        playersDataTable.getColumnModel().getColumn(12).setHeaderValue("5 Wickets/Innings");

        retrievePlayerDataPanel.setBackground(new java.awt.Color(211, 225, 255));
        retrievePlayerDataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        playersFromLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playersFromLabel.setText("Get player/s");

        getPlayerFrom.setText("jTextField1");

        playersToLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playersToLabel.setText("to");

        getPlayerTo.setText("jTextField2");

        getFromToPlayersBtn.setText("Get Players");
        getFromToPlayersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFromToPlayersBtnActionPerformed(evt);
            }
        });

        getFirstLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getFirstLabel.setText("Get first");

        firstNPlayers.setText("jTextField3");

        nPlayersLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPlayersLabel.setText("players");

        getNPlayersBtn.setText("Get Players");

        getPlayersFromLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getPlayersFromLabel.setText("Get players from");

        fromCountryOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afghanistan", "Australia", "Bangladesh", "Bermuda", "Canada", "England", "India", "Ireland", "Kenya", "Netherlands", "New Zealand", "Pakistan", "Scotland", "South Africa", "Sri Lanka", "West Indies", "Zimbabwe" }));
        fromCountryOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCountryOptionActionPerformed(evt);
            }
        });

        getPlayersFromCountryBtn.setText("Get Players");

        javax.swing.GroupLayout retrievePlayerDataPanelLayout = new javax.swing.GroupLayout(retrievePlayerDataPanel);
        retrievePlayerDataPanel.setLayout(retrievePlayerDataPanelLayout);
        retrievePlayerDataPanelLayout.setHorizontalGroup(
            retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retrievePlayerDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playersFromLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getFirstLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getPlayersFromLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(retrievePlayerDataPanelLayout.createSequentialGroup()
                        .addComponent(getPlayerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playersToLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getPlayerTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(retrievePlayerDataPanelLayout.createSequentialGroup()
                        .addComponent(firstNPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nPlayersLabel))
                    .addComponent(fromCountryOption, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getFromToPlayersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(getNPlayersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getPlayersFromCountryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        retrievePlayerDataPanelLayout.setVerticalGroup(
            retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retrievePlayerDataPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersFromLabel)
                    .addComponent(getPlayerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playersToLabel)
                    .addComponent(getPlayerTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getFromToPlayersBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getFirstLabel)
                    .addComponent(firstNPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nPlayersLabel)
                    .addComponent(getNPlayersBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(retrievePlayerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPlayersFromLabel)
                    .addComponent(fromCountryOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getPlayersFromCountryBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        countryVsCountryPanel.setBackground(new java.awt.Color(211, 225, 255));
        countryVsCountryPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        compareStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compare Average Balls Bowled", "Compare Average Bowling Averages", "Compare Average Career Lengths", "Compare Average Economy Rates", "Compare Average Number of 5 Wicket Innings", "Compare Average Innings Played", "Compare Average Matches Played", "Compare Average Runs Conceded", "Compare Average Strike Rates", "Compare Average Wickets Taken" }));

        comparePlayerStatsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comparePlayerStatsLabel.setText("Compare Player Stats - Country vs Country");

        comparePlayerStatsBtn.setText("Display Graph");

        graphDisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
        graphDisplayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        javax.swing.GroupLayout graphDisplayPanelLayout = new javax.swing.GroupLayout(graphDisplayPanel);
        graphDisplayPanel.setLayout(graphDisplayPanelLayout);
        graphDisplayPanelLayout.setHorizontalGroup(
            graphDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphDisplayPanelLayout.setVerticalGroup(
            graphDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout countryVsCountryPanelLayout = new javax.swing.GroupLayout(countryVsCountryPanel);
        countryVsCountryPanel.setLayout(countryVsCountryPanelLayout);
        countryVsCountryPanelLayout.setHorizontalGroup(
            countryVsCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countryVsCountryPanelLayout.createSequentialGroup()
                .addGroup(countryVsCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(countryVsCountryPanelLayout.createSequentialGroup()
                        .addGroup(countryVsCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(countryVsCountryPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(compareStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comparePlayerStatsBtn))
                            .addGroup(countryVsCountryPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(comparePlayerStatsLabel)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(countryVsCountryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(graphDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        countryVsCountryPanelLayout.setVerticalGroup(
            countryVsCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countryVsCountryPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(comparePlayerStatsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(countryVsCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compareStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comparePlayerStatsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(211, 225, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));
        jPanel8.setMaximumSize(new java.awt.Dimension(469, 392));

        displayPlayerAveragesBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayPlayerAveragesBtn.setText("Display Player Data Averages");

        promptLabel.setText("(from selection in table above)");

        aveCareerSpanLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveCareerSpanLabel.setText("Career Span:");

        aveCareerSpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveCareerSpan.setName("careerSpan"); // NOI18N

        aveCareerLengthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveCareerLengthLabel.setText("Career Length:");

        aveCareerLength.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveCareerLength.setName("careerLength"); // NOI18N

        aveMatchesPlayedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveMatchesPlayedLabel.setText("Matches Played:");

        aveMatchesPlayed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveMatchesPlayed.setName("matchesPlayed"); // NOI18N

        aveInningsPlayedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveInningsPlayedLabel.setText("Innings Played:");

        aveInningsPlayed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveInningsPlayed.setName("inningsPlayed"); // NOI18N

        aveBallsBowledLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveBallsBowledLabel.setText("Balls Bowled:");

        aveBallsBowled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveBallsBowled.setName("ballsBowled"); // NOI18N

        aveRunsConcededLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveRunsConcededLabel.setText("Runs Conceded:");

        aveRunsConceded.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveRunsConceded.setName("runsConceded"); // NOI18N

        aveWicketsTakenLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveWicketsTakenLabel.setText("Wickets Taken:");

        aveWicketsTaken.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveWicketsTaken.setName("wicketsTaken"); // NOI18N

        aveBowlingAverageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveBowlingAverageLabel.setText("Bowling Average:");

        aveBowlingAverage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveBowlingAverage.setName("bowlingAverage"); // NOI18N

        aveEconomyRateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveEconomyRateLabel.setText("Economy Rate:");

        aveEconomyRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveEconomyRate.setName("economyRate"); // NOI18N

        aveStrikeRateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aveStrikeRateLabel.setText("Strike Rate:");

        aveStrikeRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveStrikeRate.setName("strikeRate"); // NOI18N

        ave5wicketsInningsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ave5wicketsInningsLabel.setText("5 Wickets / Innings:");

        aveFiveWicketsPerInnings.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aveFiveWicketsPerInnings.setName("5wicketsPerInnings"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPlayerAveragesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(aveCareerLengthLabel)
                        .addComponent(aveMatchesPlayedLabel)
                        .addComponent(aveInningsPlayedLabel)
                        .addComponent(aveBallsBowledLabel)
                        .addComponent(aveRunsConcededLabel)
                        .addComponent(aveWicketsTakenLabel)
                        .addComponent(aveBowlingAverageLabel)
                        .addComponent(aveEconomyRateLabel)
                        .addComponent(aveStrikeRateLabel)
                        .addComponent(ave5wicketsInningsLabel)
                        .addComponent(aveCareerSpanLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aveInningsPlayed)
                        .addComponent(aveBallsBowled)
                        .addComponent(aveRunsConceded)
                        .addComponent(aveWicketsTaken)
                        .addComponent(aveBowlingAverage)
                        .addComponent(aveEconomyRate)
                        .addComponent(aveStrikeRate)
                        .addComponent(aveFiveWicketsPerInnings)
                        .addComponent(aveCareerSpan)
                        .addComponent(aveCareerLength)
                        .addComponent(aveMatchesPlayed))
                    .addContainerGap(97, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayPlayerAveragesBtn)
                    .addComponent(promptLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveCareerSpanLabel)
                        .addComponent(aveCareerSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveCareerLengthLabel)
                        .addComponent(aveCareerLength))
                    .addGap(13, 13, 13)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveMatchesPlayedLabel)
                        .addComponent(aveMatchesPlayed))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveInningsPlayedLabel)
                        .addComponent(aveInningsPlayed))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveBallsBowledLabel)
                        .addComponent(aveBallsBowled))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveRunsConcededLabel)
                        .addComponent(aveRunsConceded))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveWicketsTakenLabel)
                        .addComponent(aveWicketsTaken))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aveBowlingAverageLabel)
                        .addComponent(aveBowlingAverage))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aveEconomyRateLabel)
                        .addComponent(aveEconomyRate))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aveStrikeRateLabel)
                        .addComponent(aveStrikeRate))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ave5wicketsInningsLabel)
                        .addComponent(aveFiveWicketsPerInnings))
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        closeBtn1.setText("Close Application");
        closeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtn1ActionPerformed(evt);
            }
        });

        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balls Bowled", "Bowling Average", "Career Span", "Country Name", "Economy Rate", "5 Wickets/Innings", "Innings Played", "Matches Played", "Player Name", "Runs Conceded", "Strike Rate", "Wickets Taken (default)" }));

        sortByLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sortByLabel.setText("Sort By");

        sortBtn.setText("Go");

        javax.swing.GroupLayout multiplePlayerStatsPanelLayout = new javax.swing.GroupLayout(multiplePlayerStatsPanel);
        multiplePlayerStatsPanel.setLayout(multiplePlayerStatsPanelLayout);
        multiplePlayerStatsPanelLayout.setHorizontalGroup(
            multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplePlayerStatsPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multiplePlayerStatsPanelLayout.createSequentialGroup()
                        .addComponent(multiplePlayerStatsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addComponent(getAllPlayersBtn)
                        .addGap(353, 353, 353)
                        .addComponent(sortByLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortBtn)
                        .addGap(8, 8, 8))
                    .addComponent(playersDataScrollTable)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplePlayerStatsPanelLayout.createSequentialGroup()
                        .addGroup(multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeBtn1)
                            .addComponent(retrievePlayerDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryVsCountryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        multiplePlayerStatsPanelLayout.setVerticalGroup(
            multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplePlayerStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiplePlayerStatsLabel)
                    .addGroup(multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(getAllPlayersBtn)
                        .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sortByLabel)
                        .addComponent(sortBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playersDataScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(multiplePlayerStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multiplePlayerStatsPanelLayout.createSequentialGroup()
                        .addComponent(retrievePlayerDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(closeBtn1))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(countryVsCountryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainAppTabPane.addTab("Stats Involving Multiple Players", multiplePlayerStatsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainAppTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainAppTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        if(evt.getSource() == closeBtn)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void confirmGraphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmGraphBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmGraphBtnActionPerformed

    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        if(evt.getSource() == closeBtn1)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtn1ActionPerformed

    private void fromCountryOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCountryOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCountryOptionActionPerformed

    private void getFromToPlayersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFromToPlayersBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getFromToPlayersBtnActionPerformed

    private void getAllPlayersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllPlayersBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getAllPlayersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            @Override
            public void run() {
                ArrayList<Player> players = new ArrayList<Player>();
                ReadInStats worker = new ReadInStats();
                worker.load(players);
                new AppInterface(players).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ave5wicketsInningsLabel;
    private javax.swing.JLabel aveBallsBowled;
    private javax.swing.JLabel aveBallsBowledLabel;
    private javax.swing.JLabel aveBowlingAverage;
    private javax.swing.JLabel aveBowlingAverageLabel;
    private javax.swing.JLabel aveCareerLength;
    private javax.swing.JLabel aveCareerLengthLabel;
    private javax.swing.JLabel aveCareerSpan;
    private javax.swing.JLabel aveCareerSpanLabel;
    private javax.swing.JLabel aveEconomyRate;
    private javax.swing.JLabel aveEconomyRateLabel;
    private javax.swing.JLabel aveFiveWicketsPerInnings;
    private javax.swing.JLabel aveInningsPlayed;
    private javax.swing.JLabel aveInningsPlayedLabel;
    private javax.swing.JLabel aveMatchesPlayed;
    private javax.swing.JLabel aveMatchesPlayedLabel;
    private javax.swing.JLabel aveRunsConceded;
    private javax.swing.JLabel aveRunsConcededLabel;
    private javax.swing.JLabel aveStrikeRate;
    private javax.swing.JLabel aveStrikeRateLabel;
    private javax.swing.JLabel aveWicketsTaken;
    private javax.swing.JLabel aveWicketsTakenLabel;
    private javax.swing.JLabel ballsBowled;
    private javax.swing.JLabel ballsBowledLabel;
    private javax.swing.JLabel bowlingAverage;
    private javax.swing.JLabel bowlingAverageLabel;
    private javax.swing.JLabel careerLength;
    private javax.swing.JLabel careerLengthLabel;
    private javax.swing.JLabel careerSpan;
    private javax.swing.JLabel careerSpanLabel;
    private javax.swing.JLabel chooseGraphLabel;
    private javax.swing.JComboBox chooseGraphOption;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton closeBtn1;
    private javax.swing.JButton comparePlayerStatsBtn;
    private javax.swing.JLabel comparePlayerStatsLabel;
    private javax.swing.JComboBox compareStatsComboBox;
    private javax.swing.JLabel compareStatsLabel;
    private javax.swing.JPanel compareStatsPanel;
    private javax.swing.JButton confirmGraphBtn;
    private javax.swing.JPanel countryFlagPanel;
    private javax.swing.JLabel countryName;
    private javax.swing.JLabel countryNameLabel;
    private javax.swing.JPanel countryVsCountryPanel;
    private javax.swing.JPanel displayGraphPanel;
    private javax.swing.JButton displayPlayerAveragesBtn;
    private javax.swing.JLabel economyRate;
    private javax.swing.JLabel economyRateLabel;
    private javax.swing.JTextField firstNPlayers;
    private javax.swing.JLabel fiveWicketsInningsLabel;
    private javax.swing.JLabel fiveWicketsPerInnings;
    private javax.swing.JComboBox fromCountryOption;
    private javax.swing.JButton getAllPlayersBtn;
    private javax.swing.JLabel getFirstLabel;
    private javax.swing.JButton getFromToPlayersBtn;
    private javax.swing.JButton getNPlayersBtn;
    private javax.swing.JTextField getPlayerFrom;
    private javax.swing.JTextField getPlayerName;
    private javax.swing.JButton getPlayerStatsBtn;
    private javax.swing.JTextField getPlayerTo;
    private javax.swing.JButton getPlayersFromCountryBtn;
    private javax.swing.JLabel getPlayersFromLabel;
    private javax.swing.JPanel graphDisplayPanel;
    private javax.swing.JLabel inningsPlayed;
    private javax.swing.JLabel inningsPlayedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane mainAppTabPane;
    private javax.swing.JPanel mainPanelPlayerStats;
    private javax.swing.JLabel matchesPlayed;
    private javax.swing.JLabel matchesPlayedLabel;
    private javax.swing.JLabel multiplePlayerStatsLabel;
    private javax.swing.JPanel multiplePlayerStatsPanel;
    private javax.swing.JLabel nPlayersLabel;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JPanel playerStatsPanel;
    private javax.swing.JScrollPane playersDataScrollTable;
    private javax.swing.JTable playersDataTable;
    private javax.swing.JLabel playersFromLabel;
    private javax.swing.JLabel playersToLabel;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JPanel retrievePlayerDataPanel;
    private javax.swing.JLabel runsConceded;
    private javax.swing.JLabel runsConcededLabel;
    private javax.swing.JLabel searchPlayerNameLabel;
    private javax.swing.JButton sortBtn;
    private javax.swing.JComboBox sortByComboBox;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JLabel strikeRate;
    private javax.swing.JLabel strikeRateLabel;
    private javax.swing.JLabel wicketsTaken;
    private javax.swing.JLabel wicketsTakenLabel;
    // End of variables declaration//GEN-END:variables
}
